import tensorflow as tf 
print(tf.__version__)
import numpy as np
#uncomment line below if not using StackedRNN
from utils import extract_time, rnn_cell, random_generator, batch_generator
#uncomment line below to use StackedRNN
#from utilsStacked import extract_time, rnn_cell, random_generator, batch_generator
import warnings
warnings.filterwarnings("ignore")
tf.keras.backend.set_floatx('float64')

def timegan(ori_data, parameters):

    # Basic Parameters
    no, seq_len, dim = np.asarray(ori_data).shape
    
    # Maximum sequence length and each sequence length
    ori_time, max_seq_len = extract_time(ori_data)
  
    def MinMaxScaler(data):
        """Min-Max Normalizer.
        
        Args:
        - data: raw data
        
        Returns:
        - norm_data: normalized data
        - min_val: minimum values (for renormalization)
        - max_val: maximum values (for renormalization)
        """    
        min_val = np.nanmin(np.nanmin(data, axis = 0), axis = 0)
        data = data - min_val
        
        max_val = np.nanmax(np.nanmax(data, axis = 0), axis = 0)
        norm_data = data / (max_val + 1e-7)
        
        return norm_data, min_val, max_val
  
    # Normalization
    ori_data, min_val, max_val = MinMaxScaler(ori_data)
              
    ## Build a RNN networks         
  
    # Network Parameters
    hidden_dim   = parameters['hidden_dim'] 
    num_layers   = parameters['num_layer']
    iterations   = parameters['iterations']
    batch_size   = parameters['batch_size']
    module_name  = parameters['module'] 
    loss_mode    = parameters['loss']
    z_dim        = dim
    gamma        = 1
    gp_weight    = 10

    def make_embedder ():
        """Embedding network between original feature space to latent space.
        
        Args for model:
        - X: input time-series features
        
        Model returns:
        - H: embeddings
        """
        embedder_model = tf.keras.Sequential(name='embedder')
        #embedder_model.add(tf.keras.layers.Masking(mask_value=-1, input_shape=(seq_len,dim)))
        embedder_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len,dim)))
        for i in range(num_layers-1):
            embedder_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, hidden_dim)))
        embedder_model.add(tf.keras.layers.Dense(hidden_dim, activation='sigmoid'))

        return embedder_model

    def make_recovery ():   
        """Recovery network from latent space to original space.
        
        Args for model:
        - H: latent representation
        
        Model returns:
        - X_tilde: recovered data
        """     
        recovery_model = tf.keras.Sequential(name='recovery')
        for i in range(num_layers):
            recovery_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, hidden_dim)))
        recovery_model.add(tf.keras.layers.Dense(dim, activation='sigmoid'))

        return recovery_model
  
    def make_generator ():  
        """Generator function: Generate time-series data in latent space.
        
        Args for model:
        - Z: random variables
        
        MOdel returns:
        - E: generated embedding
        """ 
        generator_model = tf.keras.Sequential(name='generator')
        generator_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, dim)))
        for i in range(num_layers-1):
            generator_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, hidden_dim)))
        generator_model.add(tf.keras.layers.Dense(hidden_dim, activation='sigmoid'))

        return generator_model

    def make_supervisor (): 
        """Generate next sequence using the previous sequence.
        
        Args for model:
        - H: latent representation
        
        Model returns:
        - S: generated sequence based on the latent representations generated by the generator
        """     
        supervisor_model = tf.keras.Sequential(name='supervisor')
        for i in range(num_layers-1):
            supervisor_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, hidden_dim)))
        supervisor_model.add(tf.keras.layers.Dense(hidden_dim, activation='sigmoid'))

        return supervisor_model
    
    def make_discriminator ():   
        """Recovery network from latent space to original space.
        
        Args for model:
        - H: latent representation
        
        MOdel returns:
        - Y_hat: classification results between original and synthetic time-series
        """     
        discriminator_model = tf.keras.Sequential(name='discriminator')
        for i in range(num_layers):
            discriminator_model.add(rnn_cell(module_name, hidden_dim, return_sequences=True, input_shape=(seq_len, hidden_dim)))
        discriminator_model.add(tf.keras.layers.Dense(1, activation=None))

        return discriminator_model

    # make the models
    embedder_model = make_embedder()
    recovery_model = make_recovery()
    generator_model = make_generator()
    supervisor_model = make_supervisor()
    discriminator_model = make_discriminator()

    def get_embedder_T0_loss(X, X_tilde):
        mse = tf.keras.losses.MeanSquaredError() 
        E_loss_T0 = mse(X, X_tilde)
        return E_loss_T0

    def get_embedder_0_loss(X, X_tilde): 
        E_loss_T0 = get_embedder_T0_loss(X, X_tilde)
        E_loss0 = 10*tf.sqrt(E_loss_T0)
        return E_loss0
    
    def get_embedder_loss(X, X_tilde, H, H_hat_supervise):
        """
        computes embedder network loss

        Args:
        - X: input time-series features
        - X_tilde: recovered data
        - H: latent representation
        - H_hat_supervise: generated sequence based on the latent representations generated by the generator

        Returns:
        - E_loss: embedder loss

        """
        E_loss_T0 = get_embedder_T0_loss(X, X_tilde)
        E_loss0 = 10*tf.sqrt(E_loss_T0) #could use function above
        G_loss_S = get_generator_s_loss(H, H_hat_supervise)
        E_loss = E_loss0 + 0.1*G_loss_S
        return E_loss

    def get_generator_s_loss(H, H_hat_supervise):
        """
        computes supervised loss

        Args:
        - H: latent representation
        - H_hat_supervise: generated sequence based on the latent representations generated by the generator

        Returns:
        - G_loss_s: supervised loss for generator

        """
        mse = tf.keras.losses.MeanSquaredError()
        G_loss_S = mse(H[:,1:,:], H_hat_supervise[:,:-1,:])
        return G_loss_S

    def get_generator_loss(Y_fake, Y_fake_e, X_hat, X, H, H_hat_supervise):
        """
        computes generator loss

        Args:
        - Y_fake: classification results of latent synthetic time-series
        - Y_fake_e: classification results of generated sequence for latent synthetic time-series
        - X_hat: recovered data
        - X: input time-series data
        - H: latent representation
        - H_hat_supervise: generated sequence for latent representation

        Returns:
        - G_loss: generator loss
        - G_loss_U: unsupervised generator loss
        - G_loss_S: supervised generator loss
        - G_loss_V: moments loss for generator

        """

        #1. Adversarial loss
        if loss_mode == "bce":
            bce = tf.keras.losses.BinaryCrossentropy(from_logits=True)
            G_loss_U = bce(tf.ones_like(Y_fake), Y_fake)
            G_loss_U_e = bce(tf.ones_like(Y_fake_e), Y_fake_e)
        
        elif loss_mode == "wgan_gp":
            G_loss_U = -tf.reduce_mean(Y_fake)
            G_loss_U_e = -tf.reduce_mean(Y_fake_e)
        
        else:
            raise Exception("Loss method should be specified")

        #2. Two Moments
        X = tf.convert_to_tensor(X)
        G_loss_V1 = tf.reduce_mean(tf.abs(tf.sqrt(tf.nn.moments(X_hat,[0])[1] + 1e-6) - tf.sqrt(tf.nn.moments(X,[0])[1] + 1e-6)))
        G_loss_V2 = tf.reduce_mean(tf.abs((tf.nn.moments(X_hat,[0])[0]) - (tf.nn.moments(X,[0])[0])))
        G_loss_V = G_loss_V1 + G_loss_V2

        #3. Supervised loss
        G_loss_S = get_generator_s_loss(H, H_hat_supervise)

        #4. Summation
        G_loss = G_loss_U + gamma * G_loss_U_e + 100 * tf.sqrt(G_loss_S) + 100*G_loss_V
        return G_loss, G_loss_U, G_loss_S, G_loss_V
    
    def get_discriminator_loss(Y_real, Y_fake, Y_fake_e):
        """
        computes discrminator loss

        Args:
        - Y_real: classification results of latent real time-series
        - Y_fake: classification results of latent synthetic time-series
        - Y_fake_e: classification results of generated sequence for latent synthetic time-series

        Returns:
        - d_loss: discriminator loss

        """
        if loss_mode == "bce":
            bce = tf.keras.losses.BinaryCrossentropy(from_logits=True) #loss for cls of latent real data seq
            #default arg for tf.keras.losses.BinaryCrossentropy reduction=losses_utils.ReductionV2.AUTO
            D_loss_real = bce(tf.ones_like(Y_real), Y_real)
            D_loss_fake = bce(tf.zeros_like(Y_fake), Y_fake) 
            D_loss_fake_e = bce(tf.zeros_like(Y_fake_e), Y_fake_e) 

        #Wasserstein loss
        elif loss_mode == "wgan_gp":
            D_loss_real = -tf.reduce_mean(Y_real)
            D_loss_fake = tf.reduce_mean(Y_fake)
            D_loss_fake_e = tf.reduce_mean(Y_fake_e)
        
        else:
            raise Exception("Loss method should be specified")
            
        D_loss = D_loss_real + D_loss_fake + gamma * D_loss_fake_e

        return D_loss

    def gradient_penalty(f, H_mb, H_hat_mb):
        """
        Calculates the gradient penalty.
        This loss is calculated on an interpolated "patient"
        and added to the discriminator loss.
        """
        # get the interplated patient
        alpha = tf.random.uniform([H_mb.shape[0], 1, 1], minval=0.0, maxval=1.0, dtype=tf.float64)
        diff = H_hat_mb - H_mb
        interpolated = H_mb + alpha * diff

        with tf.GradientTape() as tape:
            tape.watch(interpolated)
            predict = f(interpolated)

        # Calculate the gradients w.r.t to this interpolated patient
        grad = tape.gradient(predict, interpolated)

        norm = tf.norm(tf.reshape(grad, [tf.shape(grad)[0], -1]), axis=1)
        gp = tf.reduce_mean((norm - 1.)**2)
        return gp


    # optimizer
    embedder0_optimizer = tf.keras.optimizers.Adam()
    embedder_optimizer = tf.keras.optimizers.Adam()
    gen_s_optimizer = tf.keras.optimizers.Adam()
    generator_optimizer = tf.keras.optimizers.Adam()
    discriminator_optimizer = tf.keras.optimizers.Adam()

    @tf.function
    def train_step_embedder(X_mb):
        """
        trains embedder model
        """

        with tf.GradientTape() as embedder_tape:
            # Embedder & Recovery
            H_mb = embedder_model(X_mb)
            X_tilde_mb = recovery_model(H_mb)

            embedder_0_loss = get_embedder_0_loss(X_mb, X_tilde_mb)
            emb_vars = embedder_model.trainable_variables + recovery_model.trainable_variables

        gradients_of_embedder = embedder_tape.gradient(embedder_0_loss, emb_vars)
        embedder0_optimizer.apply_gradients(zip(gradients_of_embedder, emb_vars))
        
        return embedder_0_loss

    @tf.function
    def train_step_generator_s(X_mb):
        """
        supervised training for generator model
        """
        
        with tf.GradientTape() as gen_s_tape: 
            
            H_mb = embedder_model(X_mb)
            
            # Generator
            H_hat_supervise_mb = supervisor_model(H_mb)

            gen_s_loss = get_generator_s_loss(H_mb, H_hat_supervise_mb) 
            gen_s_vars = supervisor_model.trainable_variables  
        gradients_of_gen_s = gen_s_tape.gradient(gen_s_loss, gen_s_vars)
        gen_s_optimizer.apply_gradients(zip(gradients_of_gen_s, gen_s_vars))

        return gen_s_loss 

    @tf.function
    def train_step_joint(X_mb, Z_mb):
        """
        join training for generator and supervisor model, embedder model
        """
        #train generator
        with tf.GradientTape() as gen_tape:
            # Generator
            H_mb = embedder_model(X_mb)
            E_hat_mb = generator_model(Z_mb)
            H_hat_mb = supervisor_model(E_hat_mb)
            H_hat_supervise_mb = supervisor_model(H_mb)

            # Synthetic data
            X_hat_mb = recovery_model(H_hat_mb)
            
            # Discriminator
            Y_fake_mb = discriminator_model(H_hat_mb)
            Y_real_mb = discriminator_model(H_mb)
            Y_fake_e_mb = discriminator_model(E_hat_mb)

            gen_loss, g_loss_u, gen_s_loss, g_loss_v = get_generator_loss(Y_fake_mb, Y_fake_e_mb, X_hat_mb, X_mb, H_mb, H_hat_supervise_mb)
            gen_vars = generator_model.trainable_variables + supervisor_model.trainable_variables

        gradients_of_gen = gen_tape.gradient(gen_loss, gen_vars)
        generator_optimizer.apply_gradients(zip(gradients_of_gen, gen_vars))

        #train embedder
        with tf.GradientTape() as embedder_tape:

            H_mb = embedder_model(X_mb)

            X_tilde_mb = recovery_model(H_mb) 

            H_hat_supervise = supervisor_model(H_mb)
            
            #i think we are minimizing E_loss but printing out E_loss_T0??
            emb_T0_loss = get_embedder_T0_loss(X_mb, X_tilde_mb)
            emb_loss = get_embedder_loss(X_mb, X_tilde_mb, H_mb, H_hat_supervise) 
            emb_vars = embedder_model.trainable_variables + recovery_model.trainable_variables

        gradients_of_emb = embedder_tape.gradient(emb_loss, emb_vars)
        embedder_optimizer.apply_gradients(zip(gradients_of_emb, emb_vars))
        
        return emb_T0_loss, emb_loss, g_loss_u, gen_s_loss, g_loss_v #H_hat_mb, E_hat_mb, 

    @tf.function
    def train_step_discriminator(X_mb, Z_mb):
        """
        trains discriminator model
        """
        
        with tf.GradientTape() as disc_tape:
            
            H_mb = embedder_model(X_mb)
            E_hat_mb = generator_model(Z_mb)
            H_hat_mb = supervisor_model(E_hat_mb)
            
            # Synthetic data
            X_hat_mb = recovery_model(H_hat_mb)
            
            # Discriminator
            Y_fake_mb = discriminator_model(H_hat_mb)
            Y_real_mb = discriminator_model(H_mb)
            Y_fake_e_mb = discriminator_model(E_hat_mb)

            # Check discriminator loss before updating
            disc_loss = get_discriminator_loss(Y_real_mb, Y_fake_mb, Y_fake_e_mb)
           
            if loss_mode == "wgan_gp":
                gp = gradient_penalty(discriminator_model, H_mb, H_hat_mb)
                disc_loss = gp * gp_weight + disc_loss

        # Train discriminator (only when the discriminator does not work well)
        if (disc_loss > 0.15):
            disc_vars = discriminator_model.trainable_variables
            gradients_of_disc = disc_tape.gradient(disc_loss, disc_vars)
        
            discriminator_optimizer.apply_gradients(zip(gradients_of_disc, disc_vars))
        
        return disc_loss

    #timeGAN training
    def train():
        
        #1. Embedding network training
        print('Start Embedding Network Training')

        for itt in range(iterations):
            # Set mini-batch
            X_mb, T_mb = batch_generator(ori_data, ori_time, batch_size)
            # Train embedder
            step_e_loss = train_step_embedder(X_mb)
           
            # Checkpoint
            if itt % 100 == 0:
                print('step: '+ str(itt) + '/' + str(iterations) + ', e_loss: ' + str(np.round(np.sqrt(step_e_loss),4)) )

        print('Finish Embedding Network Training')
        
        #2. Training only with supervised loss
        print('Start Training with Supervised Loss Only')

        for itt in range(iterations):
            # Set mini-batch
            X_mb, T_mb = batch_generator(ori_data, ori_time, batch_size)
            # Random vector generation 
            # Train generator
            step_gen_s_loss = train_step_generator_s(X_mb)

            # Checkpoint
            if itt % 100 == 0:
                print('step: '+ str(itt)  + '/' + str(iterations) +', s_loss: ' + str(np.round(np.sqrt(step_gen_s_loss),4)) )

        print('Finish Training with Supervised Loss Only')
        
        # 3. Joint Training
        print('Start Joint Training')

        for itt in range(iterations):
            # Generator training (twice more than discriminator training)
            for kk in range(2):
                # Set mini-batch
                X_mb, T_mb = batch_generator(ori_data, ori_time, batch_size)
                # Random vector generation 
                Z_mb = random_generator(batch_size, z_dim, T_mb, max_seq_len)
                # Train generator and embedder
                emb_T0_loss, emb_loss, g_loss_u, gen_s_loss, g_loss_v = train_step_joint(X_mb, Z_mb)

            # Discriminator training        
            # Set mini-batch
            X_mb, T_mb = batch_generator(ori_data, ori_time, batch_size)
            # Random vector generation 
            Z_mb = random_generator(batch_size, z_dim, T_mb, max_seq_len)
            #train discriminator
            d_loss = train_step_discriminator(X_mb, Z_mb)

            # Print multiple checkpoints
            if itt % 100 == 0:
                print('step: '+ str(itt) + '/' + str(iterations) + 
                    ', d_loss: ' + str(np.round(d_loss,4)) + 
                    ', g_loss_u: ' + str(np.round(g_loss_u,4)) + 
                    ', g_loss_s: ' + str(np.round(np.sqrt(gen_s_loss),4)) + 
                    ', g_loss_v: ' + str(np.round(g_loss_v,4)) + 
                    ', e_loss_t0: ' + str(np.round(np.sqrt(emb_T0_loss),4))  )
        
        print('Finish Joint Training')
        
        ## Synthetic data generation
        Z_mb = random_generator(no, z_dim, ori_time, max_seq_len)
        E_hat_generated = generator_model(Z_mb)
        H_hat_generated = supervisor_model(E_hat_generated)
        generated_data_curr = recovery_model(H_hat_generated)

        generated_data = list()

        for i in range(no):
            temp = generated_data_curr[i,:ori_time[i],:]
            generated_data.append(temp)
                
        # Renormalization
        generated_data = generated_data * max_val
        generated_data = generated_data + min_val
    
        return generated_data
        
    return train()


####TESTING####

# from data_loading import real_data_loading, sine_data_generation

# data_name = 'prism'
# seq_len = 10

# if data_name in ['stock', 'energy', 'sine_sampling', 'prism']:
#  ori_data = real_data_loading(data_name, seq_len)
# elif data_name == 'sine':
#   # Set number of samples and its dimensions
#   no, dim = 15, 5
#   ori_data = sine_data_generation(no, seq_len, dim)
    
# print(data_name + ' dataset is ready.')

# ## Newtork parameters
# parameters = dict()

# parameters['module'] = 'lstm' 
# parameters['hidden_dim'] = 3
# parameters['num_layer'] = 3
# parameters['iterations'] = 2
# parameters['batch_size'] = 2
# parameters['loss'] = "bce"

# generated_data = timegan(ori_data, parameters)
# print('Finish Synthetic Data Generation')
# print(generated_data)